### ISSUE TITLE
When I download Gif from server and play it is not transparent 

### ISSUE THREAD

**Issue by JameelQureshi** [hippogamesunity/SimpleGif#4]

**Comment by hippogamesunity** [comment]
Any sample/URL?

**Comment by hippogamesunity** [comment]
Yes, it's the same as https://github.com/hippogamesunity/SimpleGif/issues/3. Please wait for resolution.

**Comment by hippogamesunity** [comment]
Fixed in version 1.7. Will be available in a few days. Good luck!

**Comment by hippogamesunity** [comment]
https://stackoverflow.com/questions/48015999/interpretation-of-background-colour-index-in-gif-specification
